//! Determinism-seam proof: the exposed clock and seeded RNG are deterministic
//! under hermetic replay. This file gates on `instrument` alone (not `axum`,
//! unlike `instrument_replay.rs`), so it compiles and runs under the crate
//! gate `cargo test -p reproit-backend --features instrument,pg`.
#![cfg(feature = "instrument")]

use reproit_backend::determinism::{self, SeededRng};

const SEED_HEX: &str = "00ff00ff00ff00ff";
const OBSERVED_AT_MS: u64 = 1_753_747_200_000;

/// The seeded stream is reproducible and matches the documented xorshift64*
/// values: same seed, identical sequence across two independent instances, and
/// the same first draw the Node `Math.random` replacement produces. No replay
/// session and no environment: this asserts the pure stream shape.
#[test]
fn seeded_rng_is_reproducible_and_matches_the_documented_stream() {
    // Two independent streams from one seed draw the identical f64 sequence.
    let mut a = SeededRng::from_seed_hex(SEED_HEX).expect("seed");
    let mut b = SeededRng::from_seed_hex(SEED_HEX).expect("seed");
    let seq_a: Vec<f64> = (0..5).map(|_| a.next_f64()).collect();
    let seq_b: Vec<f64> = (0..5).map(|_| b.next_f64()).collect();
    assert_eq!(seq_a, seq_b);

    // The raw u64 stream is reproducible the same way.
    let mut a = SeededRng::from_seed_hex(SEED_HEX).expect("seed");
    let mut b = SeededRng::from_seed_hex(SEED_HEX).expect("seed");
    let raw_a: Vec<u64> = (0..5).map(|_| a.next_u64()).collect();
    let raw_b: Vec<u64> = (0..5).map(|_| b.next_u64()).collect();
    assert_eq!(raw_a, raw_b);

    // The documented first draw, generated by the Node reference over the same
    // seed: the raw u64 and its top-53-bit f64 projection.
    assert_eq!(
        SeededRng::from_seed_hex(SEED_HEX).unwrap().next_u64(),
        0xdfcb_a3b3_cf67_4a06
    );
    assert_eq!(
        SeededRng::from_seed_hex(SEED_HEX).unwrap().next_f64(),
        0.8742010416021034
    );
    // f64 is exactly the top 53 bits of the raw draw: one stream shape, not two.
    assert_eq!(seq_a[0], (raw_a[0] >> 11) as f64 / (1u64 << 53) as f64);
}

/// Under replay the seam pins the clock to the capture instant and seeds the
/// RNG from the envelope `replaySeed`, and the `instrument` re-export draws the
/// same stream. This is the only test in the file that touches the replay
/// session, so it alone sets `REPROIT_REPLAY` (latched process-wide once).
#[test]
fn replay_pins_the_clock_and_seeds_the_rng_from_the_envelope() {
    let dir = std::env::temp_dir().join(format!("reproit-rs-determinism-{}", std::process::id()));
    std::fs::create_dir_all(&dir).expect("mkdir");
    let capture = dir.join("capture.json");
    let payload = serde_json::json!({
        "format": "reproit-backend-capture",
        "version": 2,
        "operation": "GET /quote",
        "oracle": "backend-server-error",
        "envelope": {"observedAtMs": OBSERVED_AT_MS, "tz": "Europe/Berlin",
                     "replaySeed": SEED_HEX},
        "events": [],
    });
    std::fs::write(&capture, serde_json::to_vec(&payload).expect("payload")).expect("write");
    std::env::set_var("REPROIT_REPLAY", &capture);
    // Pin the envelope before any time-sensitive read.
    reproit_backend::instrument::init();

    assert!(determinism::replaying());
    // The clock reads the capture instant; the offset drifts with real time, so
    // assert within a generous window past the pinned moment.
    let now = determinism::now_millis();
    assert!(
        (OBSERVED_AT_MS..OBSERVED_AT_MS + 300_000).contains(&now),
        "clock pinned to the capture moment, got {now}"
    );

    // The pinned RNG draws the exact stream a bare SeededRng from the envelope
    // seed draws, proving the seed makes the replay reproducible run to run.
    let mut expected = SeededRng::from_seed_hex(SEED_HEX).unwrap();
    let mut pinned = determinism::replay_rng().expect("replay rng");
    for _ in 0..5 {
        assert_eq!(pinned.next_f64(), expected.next_f64());
    }

    // The instrument-namespace re-export is the SAME stream, not a second one.
    let mut via_instrument = reproit_backend::instrument::replay_rng().expect("instrument rng");
    assert_eq!(
        via_instrument.next_f64(),
        SeededRng::from_seed_hex(SEED_HEX).unwrap().next_f64()
    );

    let _ = std::fs::remove_dir_all(&dir);
}
