#!/usr/bin/env python3
"""Reject overlong lines in owned source and configuration files."""

from pathlib import Path
import subprocess
import sys


MAX_COLUMNS = 100
CHECKED_SUFFIXES = {
    ".c",
    ".cc",
    ".cpp",
    ".cs",
    ".css",
    ".dart",
    ".go",
    ".gradle",
    ".h",
    ".hpp",
    ".html",
    ".js",
    ".jsx",
    ".kt",
    ".kts",
    ".md",
    ".mjs",
    ".ps1",
    ".py",
    ".rs",
    ".sh",
    ".swift",
    ".toml",
    ".ts",
    ".tsx",
    ".xaml",
    ".xml",
    ".yaml",
    ".yml",
}


def is_generated_or_vendored(path: Path) -> bool:
    name = path.as_posix()
    return (
        "/node_modules/" in f"/{name}"
        or "/target/" in f"/{name}"
        or "/.reproit/" in f"/{name}"
        or "/artifacts/" in f"/{name}"
        or name.startswith("runners/a2ui/fixtures/")
        or name.startswith("sdk/reproit-tauri/permissions/autogenerated/")
        or (name.startswith("validation/") and path.name == "REPORT.md")
    )


def is_markdown_table(line: str, path: Path) -> bool:
    return path.suffix.lower() == ".md" and line.lstrip().startswith("|")


def repository_files() -> list[Path]:
    output = subprocess.check_output(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"]
    )
    return [Path(name) for name in output.decode().split("\0") if name]


def main() -> int:
    failures: list[str] = []
    for path in repository_files():
        if path.suffix.lower() not in CHECKED_SUFFIXES or is_generated_or_vendored(path):
            continue
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except (UnicodeDecodeError, OSError):
            continue
        for number, line in enumerate(lines, 1):
            columns = len(line.expandtabs(4))
            if columns > MAX_COLUMNS and not is_markdown_table(line, path):
                failures.append(f"{path}:{number}: {columns} columns")

    if not failures:
        return 0
    print(f"Owned text must fit within {MAX_COLUMNS} columns:")
    print("\n".join(failures))
    return 1


if __name__ == "__main__":
    sys.exit(main())
