use serde_json::Value;
use std::collections::BTreeSet;

// The oracle categories a finding can belong to (docs/cli.md "Oracles").
// `--only`/`--no` filter on these. `as_str` is the canonical lowercase tag.
//
// The `Oracle` enum and the `ORACLES` table are GENERATED by build.rs from
// `crates/reproit/oracle-registry.json`, which is also the cross-repo contract
// the cloud derives its severity ranking from. Adding a category is an edit to
// that registry plus whatever behavior it needs; the plumbing cannot drift
// from the contract because it is no longer written twice.
include!(concat!(env!("OUT_DIR"), "/oracle_generated.rs"));

/// One row of oracle metadata: everything the CLI knows about a category
/// besides its evaluation logic. `as_str`, `parse`, `classify`, and the
/// stable default set all derive from `ORACLES`, which build.rs generates
/// from `oracle-registry.json`.
pub struct OracleMeta {
    pub oracle: Oracle,
    /// Canonical lowercase tag stamped on findings; the registry id.
    pub id: &'static str,
    /// Finding `invariant` ids that classify into this category.
    pub invariants: &'static [&'static str],
    /// Finding `kind` tokens (uppercase) that classify into this category.
    pub kinds: &'static [&'static str],
    /// Member of the stable default surface (registry `stable_defaults`);
    /// every stable oracle has an authoritative predicate and an exact
    /// replay branch.
    pub stable: bool,
}

impl Oracle {
    fn meta(self) -> &'static OracleMeta {
        ORACLES
            .iter()
            .find(|m| m.oracle == self)
            .expect("every Oracle variant has an ORACLES row")
    }

    pub fn as_str(self) -> &'static str {
        self.meta().id
    }

    /// Parse one canonical category id. Unrecognized names return None so the
    /// caller can report them rather than silently choosing another oracle.
    pub fn parse(name: &str) -> Option<Oracle> {
        let name = name.trim().to_ascii_lowercase();
        ORACLES
            .iter()
            .find(|metadata| metadata.id == name)
            .map(|m| m.oracle)
    }
}

/// Classify a finding Value into an oracle category, mapping from the finding's
/// `invariant` id (preferred) or its `kind`. The invariant/kind taxonomy
/// already exists (modes/fuzz.rs, model/invariants.rs); this is the single
/// mapping from that taxonomy to the user-facing oracle categories.
pub fn classify(finding: &Value) -> Oracle {
    if matches!(
        finding.get("oracle").and_then(Value::as_str),
        Some("contract")
    ) {
        return Oracle::Contract;
    }
    let invariant = finding
        .get("invariant")
        .and_then(Value::as_str)
        .unwrap_or("");
    if !invariant.is_empty() {
        if let Some(m) = ORACLES.iter().find(|m| m.invariants.contains(&invariant)) {
            return m.oracle;
        }
    }
    let kind = finding
        .get("kind")
        .and_then(Value::as_str)
        .unwrap_or("")
        .to_ascii_uppercase();
    // Raw framework exception blocks predate the named no-exception invariant
    // (kinds EXCEPTION/CRASH/SIGNAL plus the "EXCEPTION CAUGHT BY ..." prose
    // prefix). They are still objective crashes. Everything else stays ABSTAIN
    // so registry drift cannot masquerade as a confirmed crash.
    if kind.starts_with("EXCEPTION CAUGHT BY") {
        return Oracle::Crash;
    }
    ORACLES
        .iter()
        .find(|m| m.kinds.contains(&kind.as_str()))
        .map(|m| m.oracle)
        .unwrap_or(Oracle::Unclassified)
}

/// An oracle include/exclude filter built from `--only` / `--no`. Default
/// (neither set) is the stable, high-confidence product set. `--only` can opt
/// into any preview/experimental detector; `--no`
/// removes the listed set. When both are given, `--only` is applied first then
/// `--no` subtracts, so `--only crash,jank --no jank` == `crash`.
#[derive(Clone, Debug)]
pub struct OracleFilter {
    only: Option<BTreeSet<&'static str>>,
    no: BTreeSet<&'static str>,
}

impl OracleFilter {
    /// Build from the raw comma-separated `--only`/`--no` strings. Unrecognized
    /// category names are returned (second tuple element) so the caller can
    /// warn without failing the run.
    pub fn build(only: Option<&str>, no: Option<&str>) -> (OracleFilter, Vec<String>) {
        let mut unknown = Vec::new();
        let parse_set = |raw: &str, unknown: &mut Vec<String>| -> BTreeSet<&'static str> {
            let mut set = BTreeSet::new();
            for tok in raw.split(',') {
                let t = tok.trim();
                if t.is_empty() {
                    continue;
                }
                match Oracle::parse(t) {
                    Some(o) => {
                        set.insert(o.as_str());
                    }
                    None => unknown.push(t.to_string()),
                }
            }
            set
        };
        let only_set = match only {
            Some(s) => Some(parse_set(s, &mut unknown)),
            None => Some(Self::stable_set()),
        };
        let no_set = no.map(|s| parse_set(s, &mut unknown)).unwrap_or_default();
        (
            OracleFilter {
                only: only_set,
                no: no_set,
            },
            unknown,
        )
    }

    /// All categories on, nothing filtered (the default when no flags are set).
    pub fn all() -> Self {
        OracleFilter {
            only: None,
            no: BTreeSet::new(),
        }
    }

    /// Default product surface. These detectors describe an objective failure
    /// and have a direct replay predicate. Specialist, timing-sensitive, or
    /// heuristic detectors remain available through `--only` without being
    /// allowed to create noisy default findings.
    pub fn stable() -> Self {
        OracleFilter {
            only: Some(Self::stable_set()),
            no: BTreeSet::new(),
        }
    }

    pub(super) fn stable_set() -> BTreeSet<&'static str> {
        ORACLES.iter().filter(|m| m.stable).map(|m| m.id).collect()
    }

    /// Whether a given oracle category passes the filter.
    pub fn allows(&self, oracle: Oracle) -> bool {
        // Unclassified taxonomy is telemetry about registry drift, never a bug class.
        // It cannot be opted into, including through the internal all() filter.
        if oracle == Oracle::Unclassified {
            return false;
        }
        let tag = oracle.as_str();
        if let Some(only) = &self.only {
            if !only.contains(tag) {
                return false;
            }
        }
        !self.no.contains(tag)
    }

    /// Partition findings into (kept, dropped) by the filter, tagging every
    /// KEPT finding with its `oracle` category (in place). Dropped findings
    /// are returned untagged so the caller can count/report them.
    pub fn apply(&self, findings: Vec<Value>) -> (Vec<Value>, Vec<Value>) {
        let mut kept = Vec::new();
        let mut dropped = Vec::new();
        for mut f in findings {
            let oracle = classify(&f);
            if self.allows(oracle) {
                if let Some(obj) = f.as_object_mut() {
                    obj.insert(
                        "oracle".to_string(),
                        Value::String(oracle.as_str().to_string()),
                    );
                    // Preserve specialist detectors as useful output while
                    // enforcing the confirmation boundary before IDs, shrink,
                    // persistence, or Cloud upload. Repeatability alone cannot
                    // prove application intent.
                    if !Self::stable_set().contains(oracle.as_str()) {
                        obj.insert("advisory".to_string(), Value::Bool(true));
                        obj.insert(
                            "confidence".to_string(),
                            Value::String("candidate".to_string()),
                        );
                    }
                }
                kept.push(f);
            } else {
                dropped.push(f);
            }
        }
        (kept, dropped)
    }
}
